from node:alpine

RUN apk update && apk add --no-cache openssl tzdata
ENV TZ=Asia/Kolkata

WORKDIR /app

COPY package*.json .

RUN npm install 

COPY . .

RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "start"]
